### ISSUE TITLE
Jitter On Retry

### ISSUE THREAD

**Issue by GEverding** [kinecosystem/kin-python#1]
Adding a jitter setting to the retry config would be a good addition. https://landing.google.com/sre/sre-book/chapters/addressing-cascading-failures/

**Comment by kikengineering** [comment]
Hi there, we’re currently using a jitter of 10% on the retries (it’s set [here](https://github.com/kinecosystem/kin-python/blob/master/agora/client/client.py#L200) and you can see how it is calculated [here](https://github.com/kinecosystem/kin-python/blob/master/agora/retry/strategy.py#L105)). Our initial reasoning for not including jitter setting in the retry config is because we didn’t want any developers to _not_ use jitter when retrying.

Would you still be interested in seeing a separate setting? If so we’d definitely be interested in hearing about why/how you think it’d be useful.
